### ISSUE TITLE
web 1.2 rerevisited

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1864]
## renames

- [ ] readonly -> restrict/write
- [ ] implement other restrict/*

## KeySet features

- [ ] null keys?
- [ ] binary keys not marked
- [ ] improve usability for arrays (indexing of #0, #1, ...)

## API blueprint

- [ ] Response 204 not documented?
- [ ] how can you set metadata?
- [ ] delete recursive?

## elektrad does not start

```
npm start
> @elektra-web/elektrad@1.1.0 start /home/markus/Projekte/Elektra/libelektra/src/tools/web/elektrad
> npm run start:prod


> @elektra-web/elektrad@1.1.0 start:prod /home/markus/Projekte/Elektra/libelektra/src/tools/web/elektrad
> cross-env NODE_ENV=production DEBUG=elektrad:*,-*debug,-*log node build/

module.js:471
    throw err;
    ^

Error: Cannot find module '/home/markus/Projekte/Elektra/libelektra/src/tools/web/elektrad/build'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

npm ERR! Linux 4.9.0-6-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start:prod"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @elektra-web/elektrad@1.1.0 start:prod: `cross-env NODE_ENV=production DEBUG=elektrad:*,-*debug,-*log node build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @elektra-web/elektrad@1.1.0 start:prod script 'cross-env NODE_ENV=production DEBUG=elektrad:*,-*debug,-*log node build/'.
```

## webd does not install

```
npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[     .............] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/raw-body
@elektra-web/webd@1.1.0 /home/markus/Projekte/Elektra/libelektra/src/tools/web/webd

...
│ └── is-windows@1.0.2 
├─┬ UNMET PEER DEPENDENCY debug@3.1.0
│ └── ms@2.0.0 
...
├── eslint-config-standard@10.2.1 
├── UNMET PEER DEPENDENCY eslint-plugin-import@>=2.2.0
├── UNMET PEER DEPENDENCY eslint-plugin-node@>=4.2.2
├── eslint-plugin-promise@3.7.0
...
│ └── is-stream@1.1.0 
├── node-uuid@1.4.8 
└── UNMET PEER DEPENDENCY webpack@2 || 3 || 4
```

## ronn warnings

```
warn: unexpected text: "After building via "
warn: unrecognized block tag: "code"
warn: unexpected text: " and installing via "
warn: unrecognized block tag: "code"
warn: unexpected text: ":"
warn: unexpected text: "Install and start an elektrad instance:"
warn: unexpected text: "Install and start the client (connects to the elektrad instance):"
warn: unrecognized inline tag: "img"
warn: unrecognized block tag: "code"
warn: unexpected text: " - contains the elektra-web client (Web UI)"
warn: unexpected text: " - React components"
warn: unrecognized block tag: "code"
warn: unexpected text: " - pages in the app"
warn: unrecognized block tag: "code"
warn: unexpected text: " - contains all UI components related to a single item in the tree view"
warn: unrecognized block tag: "code"
warn: unexpected text: " - these dialogs are opened when certain actions are pressed (icons next to the tree items)"
```

**Comment by omnidan** [comment]
> elektrad does not start

Did you build the project? If running from source you need to run `npm run build` and then `npm start` (I adjusted this because it makes more sense than rebuilding every single time when running the cmake installation). I can create a new script for the cmake installation though and change `npm start` so it still works the same way as before.

> webd does not install

I do not see any errors there? The peer dependency warnings should not be a problem.

> ronn warnings

I am not sure what the problem is here, it is valid markdown (renders fine on github). Does ronn have any special limitations here?

**Comment by markus2330** [comment]
> Did you build the project?

First I tried to run "make install" but it seems like a start script is still not working and docu how to run it is missing, too?

Then I entered the source directory "webd" and tried to run `npm install && npm start`. Seems like `npm run build` actually makes a difference (although it prints many errors) but I could not find any docu about it. Nevertheless, accessing http://localhost:33334/ then fails with "Not Found" and console errors ('/home/markus/Projekte/Elektra/build-64/D` is the `DESTDIR` I used for installation):

```
Error: ENOENT: no such file or directory, stat '/home/markus/Projekte/Elektra/build-64/D/usr/local/share/elektra/tool_data/web/client/build/index.html'
```

Please write docu how it should work and always use this so that it is well tested. And please also test from a complete clean installation. (Without any earlier `npm install` executed.)

> I am not sure what the problem is here, it is valid markdown (renders fine on github).

GitHub is a very special Markdown dialect. You cannot infer from GitHub if you actually wrote broadly accepted Markdown. It is best if you try to run ronn yourself.

**Comment by omnidan** [comment]
`install (CODE "execute_process (COMMAND ${TARGET_TOOL_EXEC_FOLDER}/build-${tool})")` seems to not execute at all. executing `kdb build-web` works though (same script). I'm still trying to figure out why this isn't working, it's taking a long time because cmake always takes a long time to run...

**Comment by markus2330** [comment]
You refer to a script which might not yet be installed. Also TARGET_TOOL_EXEC_FOLDER is wrong (its not an absolute path).

**Comment by omnidan** [comment]
@markus2330 I already updated the README.md file with info on how to run it earlier.

I fixed the cmake installation issue and now it works for me with a clean installation (following the "getting started" instructions from README.md).

> GitHub is a very special Markdown dialect. You cannot infer from GitHub if you actually wrote broadly accepted Markdown. It is best if you try to run ronn yourself.

I see, the error messages `ronn` gives are not very useful though :/ I fixed those issues now. I don't know how to fix the `unrecognized inline tag: "img"` errors without removing the images completely (see #960).

BTW: to keep things simple - can we merge the 1.2 PR, close all other issues, rename this one to `elektra-web 1.3 tasks` and move all further tasks (undo/redo, updating blueprints) to 1.3 (this issue)?

BTW^2: I also noticed that `sudo make uninstall` doesn't fully uninstall elektra (at least on macOS). `kdb` is still available but every command fails:

```
dyld: Library not loaded: @rpath/libelektratools.2.dylib
  Referenced from: /usr/local/bin/kdb
  Reason: image not found
fish: 'kdb' terminated by signal SIGABRT (Abort)
```

**Comment by markus2330** [comment]
> I already updated the README.md file with info on how to run it earlier.

Thank you, unfortunately it still fails, see #1839

> I see, the error messages ronn gives are not very useful though :/ I fixed those issues now.

Thank you!

> BTW: to keep things simple - can we merge the 1.2 PR, close all other issues, rename this one to elektra-web 1.3 tasks and move all further tasks (undo/redo, updating blueprints) to 1.3 (this issue)?

Yes, I would love to but I want to be at least able to start webd before I merge.

> I also noticed that sudo make uninstall doesn't fully uninstall elektra (at least on macOS). kdb is still available but every command fails:

We fixed that some time ago: #1244
Unfortunately the build server still does not check for it so we might have a regression.

**Comment by markus2330** [comment]
Follow up:  #1865
