### ISSUE TITLE
web-ui 1.5 leftovers

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1951]
Small usability things:

- [x] When clicking left next to arrow, a subtree collapses, but does not open. When clicking right you get exactly the opposite.
- [x] ~~edit value of non-leaves does not have a way to abort~~
- [x] ~~also metadata has no way to abort~~

Other small things:

- [x] ~~Why does "run.sh" start webd and not client?~~

- [x] ~~When starting there is some unnecessary output like:~~

```
The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:
```

Other problems:

- [x] metadata does not go away afterwards (e.g. click on restrict/remove, uncheck restrict/remove, still leaves restrict/remove = 0 as metadata)

**Comment by omnidan** [comment]
> edit value of non-leaves does not have a way to abort
> also metadata has no way to abort

Elektra Web always saves values when the field is changed (this is consistent across the whole application). Instead of "aborting", there is the undo/redo feature which serves the same purpose.

> Why does "run.sh" start webd and not client?

Because webd still serves the client. Even if you run `npm start` in the client directory, it will run webd which serves the client.

**Comment by omnidan** [comment]
should be fixed in #2029

**Comment by markus2330** [comment]
most of the parts were not fixed (or at least not with Firefox ESR), I added them to #2032
