### ISSUE TITLE
Mac OSX support

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#270]
during compilation:

```
MACOSX_RPATH is not specified for the following targets:
   elektra
   elektra-full
   elektratools
   elektratools-full
```

when running `kdb`:

```
kdb(17599,0x7fff75637300) malloc: *** error for object 0x7fdb02001200: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
fish: 'kdb' terminated by signal SIGABRT (Abort)
```

**Comment by manuelm** [comment]
http://www.cmake.org/Wiki/CMake_RPATH_handling#Mac_OS_X_and_the_RPATH

**Comment by markus2330** [comment]
Did you need to modify something in order to get Elektra compiled?

Does it work with `DYLD_LIBRARY_PATH` set correctly?

**Comment by markus2330** [comment]
Any progress on Mac OSX support?

**Comment by mpranj** [comment]
Yes, I fixed the compilation issues, but it still does not run properly on OS X, just running kdb i get:

```
kdb(521,0x7fff7837c300) malloc: *** error for object 0x7fa8c4001200: pointer being freed was not allocated
```

I will look into it tomorrow!

**Comment by markus2330** [comment]
@mpranj: a pull request for compilation issues would be a good start

for the memory allocation issues: would be interesting if valgrind runs differently on Mac OS X. As last resort you can bisect and look which commit introduced the issue. Most likely its in the Mac OS X specific parts.

**Comment by mpranj** [comment]
I am currently debugging with lldb and trying to get all tests to work. It seems like its not in any OS X specific portions of the code - the problem lies in things like dirname(3) which has different behaviour on GNU vs POSIX.
(btw valgrind has no stable release for the latest OS X - so I am using a dev version)

**Comment by markus2330** [comment]
Thank you! Strange that different semantics in dirname(3) causes memory 
allocation problems.

**Comment by mpranj** [comment]
OS X manpages state that dirname points to internal storage allocated during the first call of dirname(). 
Linux manpages state that dirname(char *path) may modify the contents of given path.

The problem on OS X was that the pointer to the allocated memory was lost and thus could not be free'd.

**Comment by markus2330** [comment]
Interesting, thanks for fixing everything!

**Comment by omnidan** [comment]
just tried compiling libelektra on OS X and getting the following error:

```
/Users/dan/Development/university/libelektra/src/tools/race/race.c:13:1: error:
      unknown type name 'pthread_barrier_t'
pthread_barrier_t *bar;
^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:30:2: warning:
      implicit declaration of function 'pthread_barrier_wait' is invalid in C99
      [-Wimplicit-function-declaration]
        pthread_barrier_wait(bar);
        ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:84:2: error:
      use of undeclared identifier 'pthread_barrierattr_t'; did you mean
      'pthread_barrier_wait'?
        pthread_barrierattr_t attr;
        ^~~~~~~~~~~~~~~~~~~~~
        pthread_barrier_wait
/Users/dan/Development/university/libelektra/src/tools/race/race.c:30:2: note:
      'pthread_barrier_wait' declared here
        pthread_barrier_wait(bar);
        ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:84:23: error:
      expected ';' after expression
        pthread_barrierattr_t attr;
                             ^
                             ;
/Users/dan/Development/university/libelektra/src/tools/race/race.c:84:24: error:
      use of undeclared identifier 'attr'
        pthread_barrierattr_t attr;
                              ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:85:6: warning:
      implicit declaration of function 'pthread_barrierattr_init' is invalid in
      C99 [-Wimplicit-function-declaration]
        if (pthread_barrierattr_init(&attr) != 0)
            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:85:32: error:
      use of undeclared identifier 'attr'
        if (pthread_barrierattr_init(&attr) != 0)
                                      ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:90:6: warning:
      implicit declaration of function 'pthread_barrierattr_setpshared' is
      invalid in C99 [-Wimplicit-function-declaration]
        if (pthread_barrierattr_setpshared(&attr, PTHREAD_PROCESS_SHARED) != 0)
            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:90:38: error:
      use of undeclared identifier 'attr'
        if (pthread_barrierattr_setpshared(&attr, PTHREAD_PROCESS_SHARED) != 0)
                                            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:107:31: error:
      use of undeclared identifier 'pthread_barrier_t'; did you mean
      'pthread_barrier_wait'?
        if (ftruncate(shm_fd, sizeof(pthread_barrier_t)) != 0)
                                     ^~~~~~~~~~~~~~~~~
                                     pthread_barrier_wait
/Users/dan/Development/university/libelektra/src/tools/race/race.c:30:2: note:
      'pthread_barrier_wait' declared here
        pthread_barrier_wait(bar);
        ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:107:30: warning:
      invalid application of 'sizeof' to a function type [-Wpointer-arith]
        if (ftruncate(shm_fd, sizeof(pthread_barrier_t)) != 0)
                                    ^~~~~~~~~~~~~~~~~~~
/Users/dan/Development/university/libelektra/src/tools/race/race.c:112:26: error:
      use of undeclared identifier 'pthread_barrier_t'; did you mean
      'pthread_barrier_wait'?
        bar = mmap(NULL, sizeof(pthread_barrier_t),
                                ^~~~~~~~~~~~~~~~~
                                pthread_barrier_wait
/Users/dan/Development/university/libelektra/src/tools/race/race.c:30:2: note:
      'pthread_barrier_wait' declared here
        pthread_barrier_wait(bar);
        ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:112:25: warning:
      invalid application of 'sizeof' to a function type [-Wpointer-arith]
        bar = mmap(NULL, sizeof(pthread_barrier_t),
                               ^~~~~~~~~~~~~~~~~~~
/Users/dan/Development/university/libelektra/src/tools/race/race.c:122:6: warning:
      implicit declaration of function 'pthread_barrier_init' is invalid in C99
      [-Wimplicit-function-declaration]
        if (pthread_barrier_init(bar, &attr, num_barriers) != 0)
            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:122:33: error:
      use of undeclared identifier 'attr'
        if (pthread_barrier_init(bar, &attr, num_barriers) != 0)
                                       ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:127:6: warning:
      implicit declaration of function 'pthread_barrierattr_destroy' is invalid
      in C99 [-Wimplicit-function-declaration]
        if (pthread_barrierattr_destroy(&attr) != 0)
            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:127:35: error:
      use of undeclared identifier 'attr'
        if (pthread_barrierattr_destroy(&attr) != 0)
                                         ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:169:6: warning:
      implicit declaration of function 'pthread_barrier_destroy' is invalid in
      C99 [-Wimplicit-function-declaration]
        if (pthread_barrier_destroy(bar) != 0)
            ^
/Users/dan/Development/university/libelektra/src/tools/race/race.c:84:2: warning:
      expression result unused [-Wunused-value]
        pthread_barrierattr_t attr;
        ^~~~~~~~~~~~~~~~~~~~~
9 warnings and 10 errors generated.
make[2]: *** [src/tools/race/CMakeFiles/race.dir/race.c.o] Error 1
make[1]: *** [src/tools/race/CMakeFiles/race.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by markus2330** [comment]
you wrote:
> just tried compiling libelektra on OS X and getting the following error:

I disabled the race tool for OS X in e681a565d340721e1ae83db7cb5396386aa7a899

You can also remove tools/bindings/plugins using

    -dTOOLS="ALL;-race"

**Comment by omnidan** [comment]
Compiling worked now. When running `kdb` I get:

```
libc++abi.dylib: terminating with uncaught exception of type kdb::KDBException: 1 Warning was issued:
 Warning number: 1
	Description: could not load module, dlopen failed
	Ingroup: modules
	Module: dl
	At: /Users/dan/Development/university/libelektra/src/libloader/dl.c:80
	Reason: of module: libelektra-resolver.so, because: dlopen(libelektra-resolver.so, 1): image not found
	Mountpoint:
	Configfile:
Error (#40) occurred!
Description: Failed to open default backend (see warnings for more information)
Ingroup: kdb
Module:
At: /Users/dan/Development/university/libelektra/src/libelektra/kdb.c:199
Reason: could not open default backend
Mountpoint:
Configfile:

fish: './kdb' terminated by signal SIGABRT (Abort)
```

**Comment by markus2330** [comment]
Does `kdb-full` work? Did you try merging the PR #284

**Comment by markus2330** [comment]
Please confirm that problems are fixed or reopen issue otherwise. Thanks!

**Comment by omnidan** [comment]
`kdb-full` and `kdb-static` work fine now. `kdb` still fails with the same error.

**Comment by omnidan** [comment]
`kdb` works now with the change proposed in #289 - it still compiles fine on linux too.
