### ISSUE TITLE
Buildserver triggering not working

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3268]
- [x] "jenkins build libelektra please" and so on seem to now work (for everyone except you?) in the PRs.
- [x] master does not build automatically (e.g. 35585f7e5ae33ec4f8a97b67b094d1853c1f33d9 did not build; 20aeecee7dda4df0c88c1ee964cbe054f4256e80 was triggered manually)

Could you please make it working and/or assign everyone from ElektraInitative to be allowed to issue the buildphrases?

**Comment by markus2330** [comment]
It should be working like described in doc/BUILDSERVER.md or I am also open for improvements.

**Comment by Mistreated** [comment]
This should be fixed now. Unfortunatly, the server has a lot of stuff to do, but if someone finds a malfunction, please report it.

**Comment by markus2330** [comment]
Thank you for the quick fix.

Of course a lot goes on. But at least creating a PR should be tested on such changes.

**Comment by markus2330** [comment]
Still does not work for me:

https://github.com/ElektraInitiative/libelektra/pull/3226
https://github.com/ElektraInitiative/libelektra/pull/3098

**Comment by Mistreated** [comment]
It would be really helpful to me if I had access to the old server config.

**Comment by mpranj** [comment]
Was the build triggering problem introduced when the url was changed from http://IP to https://build.libelektra.org/ or did it not work before that either?

**Comment by Mistreated** [comment]
I thought the old server was taking the PR builds and therefore the new one didnt trigger a build. I just need a config of a plugin.

**Comment by markus2330** [comment]
@Mistreated is there something still open? You can tick the above boxes and close the issue (or suggest that we can close it if it might reappear).

**Comment by Mistreated** [comment]
Its working properly properly last time I checked and I do not think it can reappear. Closed.
