### ISSUE TITLE
Could not find mountpoint configuration

### ISSUE THREAD

**Issue by strahlex** [ElektraInitiative/libelektra#337]
I am trying to get started with libelektra. However, when I try to mount a ini file I get the following error:

    $ kdb mount launcher.ini user/foobar simpleini
    1 Warning was issued:
        Warning number: 22
        Description: Could not find any mountpoint configuration
        Ingroup: trie
        Module: 
        At: /build/elektra-Dhtdr2/elektra-0.8.7/src/libelektra/mount.c:69
        Reason: system/elektra/mountpoints
    The command mount terminated unsuccessfully with the info: Command aborted

I have installed elektra from the Debian packages under Debian Jessie. What do I wrong?

**Comment by markus2330** [comment]
Thank you for reporting this issue. The problem was already fixed in 0.8.11 (noted under Further gems in the release notes). It is, however, just a warning and not the problem you have. To fix the warning simply do:

    kdb set system/elektra/mountpoints

Your actual problem, however, is that simpleini needs an encoding and the null plugin to work. In that version the error output unfortunately was not working properly, so you cant see that this is the problem. You would need `-d` to see the problem (also fixed later). So for mounting you would use:

    kdb mount launcher.ini user/foobar simpleini ccode null

There is, however, an example in the README. To get infos about plugins use:

    kdb info simpleini

(Also spartanic in that version, for a more up-to-date version see https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/simpleini)

Note that unmounting in this version works using:

    kdb umount user_foobar

(also fixed later, now `kdb umount user/foobar` works)

simpleini is more of a demonstration plugin to show how minimal fully working plugins can be. In the jessie's version the `ni` plugin would be preferable:

    kdb mount launcer.ini user/foobar ni

Later, also the `ini` plugin appeared which is now superior in nearly every aspect. (especially preserving comments and putting them into metadata). The `ni` plugin now evolved into metadata storage for specification. (Which was not possible in jessie's version, too).

**Comment by strahlex** [comment]
Still cannot get the keys contained in my INI file. Is there a way to reset the elektra database? It looks like my mountpoints have been messed up since I mixed 0.8.7 and 0.8.13.

````
$ sudo kdb-full mount mkwrapper.ini user/test2 ini -d            
Trying to load the resolver plugin resolver
Trying to add default plugin sync
The configuration which will be set is:
system/elektra/mountpoints 
system/elektra/mountpoints/user/foobar This is a configuration for a backend, see subkeys for more information
system/elektra/mountpoints/user/foobar/config 
system/elektra/mountpoints/user/foobar/config/path launcher.ini
system/elektra/mountpoints/user/foobar/errorplugins 
system/elektra/mountpoints/user/foobar/errorplugins/#5#resolver#resolver# 
system/elektra/mountpoints/user/foobar/getplugins 
system/elektra/mountpoints/user/foobar/getplugins/#0#resolver 
system/elektra/mountpoints/user/foobar/getplugins/#5#ni#ni# 
system/elektra/mountpoints/user/foobar/mountpoint user/foobar
system/elektra/mountpoints/user/foobar/setplugins 
system/elektra/mountpoints/user/foobar/setplugins/#0#resolver 
system/elektra/mountpoints/user/foobar/setplugins/#5#ni 
system/elektra/mountpoints/user/foobar/setplugins/#6#sync#sync# 
system/elektra/mountpoints/user/foobar/setplugins/#7#resolver 
system/elektra/mountpoints/user/test This is a configuration for a backend, see subkeys for more information
system/elektra/mountpoints/user/test/config 
system/elektra/mountpoints/user/test/config/path launcher.ini
system/elektra/mountpoints/user/test/errorplugins 
system/elektra/mountpoints/user/test/errorplugins/#5#resolver#resolver# 
system/elektra/mountpoints/user/test/getplugins 
system/elektra/mountpoints/user/test/getplugins/#0#resolver 
system/elektra/mountpoints/user/test/getplugins/#5#dump#dump# 
system/elektra/mountpoints/user/test/mountpoint user/test
system/elektra/mountpoints/user/test/setplugins 
system/elektra/mountpoints/user/test/setplugins/#0#resolver 
system/elektra/mountpoints/user/test/setplugins/#5#dump 
system/elektra/mountpoints/user/test/setplugins/#6#sync#sync# 
system/elektra/mountpoints/user/test/setplugins/#7#resolver 
system/elektra/mountpoints/user\/test This is a configuration for a backend, see subkeys for more information
system/elektra/mountpoints/user\/test/config 
system/elektra/mountpoints/user\/test/config/path launcher.ini
system/elektra/mountpoints/user\/test/errorplugins 
system/elektra/mountpoints/user\/test/errorplugins/#5#resolver#resolver# 
system/elektra/mountpoints/user\/test/getplugins 
system/elektra/mountpoints/user\/test/getplugins/#0#resolver 
system/elektra/mountpoints/user\/test/getplugins/#5#ini#ini# 
system/elektra/mountpoints/user\/test/mountpoint user/test
system/elektra/mountpoints/user\/test/setplugins 
system/elektra/mountpoints/user\/test/setplugins/#0#resolver 
system/elektra/mountpoints/user\/test/setplugins/#5#ini 
system/elektra/mountpoints/user\/test/setplugins/#6#sync#sync# 
system/elektra/mountpoints/user\/test/setplugins/#7#resolver 
system/elektra/mountpoints/user\/test2 This is a configuration for a backend, see subkeys for more information
system/elektra/mountpoints/user\/test2/config 
system/elektra/mountpoints/user\/test2/config/path mkwrapper.ini
system/elektra/mountpoints/user\/test2/errorplugins 
system/elektra/mountpoints/user\/test2/errorplugins/#5#resolver#resolver# 
system/elektra/mountpoints/user\/test2/getplugins 
system/elektra/mountpoints/user\/test2/getplugins/#0#resolver 
system/elektra/mountpoints/user\/test2/getplugins/#5#ini#ini# 
system/elektra/mountpoints/user\/test2/mountpoint user/test2
system/elektra/mountpoints/user\/test2/setplugins 
system/elektra/mountpoints/user\/test2/setplugins/#0#resolver 
system/elektra/mountpoints/user\/test2/setplugins/#5#ini 
system/elektra/mountpoints/user\/test2/setplugins/#6#sync#sync# 
system/elektra/mountpoints/user\/test2/setplugins/#7#resolver 
system/elektra/mountpoints/user_test2_ serialised Backend
system/elektra/mountpoints/user_test2_/config 
system/elektra/mountpoints/user_test2_/config/path launcher.ini
system/elektra/mountpoints/user_test2_/errorplugins 
system/elektra/mountpoints/user_test2_/errorplugins/#5#resolver#resolver# 
system/elektra/mountpoints/user_test2_/getplugins 
system/elektra/mountpoints/user_test2_/getplugins/#0#resolver 
system/elektra/mountpoints/user_test2_/getplugins/#5#ni#ni# 
system/elektra/mountpoints/user_test2_/mountpoint user/test2/
system/elektra/mountpoints/user_test2_/setplugins 
system/elektra/mountpoints/user_test2_/setplugins/#0#resolver 
system/elektra/mountpoints/user_test2_/setplugins/#5#ni 
system/elektra/mountpoints/user_test2_/setplugins/#7#resolver 
````

**Comment by markus2330** [comment]
Yes, user\/test2 seems to be double mounted.

To remove all keys in mountpoints: `kdb rm -r system/elektra/mountpoints`

Or even: `rm -r /etc/kdb`

**Comment by markus2330** [comment]
I'll close the issue. Please do not hesitate to reopen or create a new issue.

**Comment by strahlex** [comment]
@markus2330 Last week was a little bit busy but I am back to work now.

Somehow I did not get the ini file mounting to work. I tried to find out why and discovered that the mount parameters expects the file to be located in the /root directory.

````
$sudo kdb-full mount mkwrapper.ini /test ini
$sudo kdb-full file user/test
/root/.config/mkwrapper.ini
````
So I tried to use
````
$sudo kdb-full mount `pwd`/mkwrapper.ini /testus ini
$sudo kdb-full file user/testus
/root/home/aroessler/projects/mkwrapper-sim/mkwrapper.ini
````
which is not my expected result. Relative paths seem not work either:
````
$ kdb-full mount ../`pwd`/mkwrapper.ini /bar ini
The command mount terminated unsuccessfully with the info:
The path you entered is invalid.
Try to add another path instead.

Filenames are typically (depending on
resolver) not allowed to contain '..'.

For more information see:
 kdb info <your resolver>
````

Is there a way to fix this problem?

**Comment by markus2330** [comment]
Of course there is ;) Make sure to read `doc/NAMESPACES.md` and `src/plugins/resolver/README.md` to be familar with the basic concepts. (kdb gave you even the hint to do `kdb info resolver`. It will [display the README of the plugin resolver](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/resolver))

The `user` namespace is relative to the home-directory, in your case `/root`. By design, you cannot escape the home-directory for the user-namespace, at least not with the standard resolver.

Absolute file-names (that are also interpreted as absolute) are only possible in the `system` namespace. So with your `testus` mountpoint, simply use the `system` namespace:
```
$sudo kdb-full mount `pwd`/mkwrapper.ini /testus ini
$sudo kdb-full file system/testus
/where/ever/pwd/was/mkwrapper.ini
```

**Comment by markus2330** [comment]
Btw. any specific reason why you use `kdb-full` and not `kdb`?

**Comment by strahlex** [comment]
Thanks, it seems to work.

I used `kdb-full` because my `kdb` installation was broken, already fixed the problem.
