### ISSUE TITLE
couldn't resolve module/action 'elektra'

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3812]
## Steps to Reproduce the Problem

```sh
pip3 install ansible
ansible-galaxy collection install elektra_initiative.libelektra
ansible localhost -m elektrafacts # successfully lists keys
ansible-playbook my-playbook.yml
```

with example from https://galaxy.ansible.com/elektra_initiative/libelektra stored as my-playbook.yml

```
- name: elektra module example
  hosts: localhost
  connection: local
  tasks:
    - name: set example values
      elektra:
        # Despite the name, this does not have to be a real mountpoint in the KDB.
        # If no plugin is specified, the value is only used as the base key for the keys object.
        mountpoint: /test/example
        # The keys object contains the data that should be present below the mountpoint.
        keys:
          fruit:
            cherry:
              value: cola
            apple:
              value: pie
            berries:
                raspberry:
                  value: pi
                blueberry:
                  value: muffin
          vegtables:
            tomato:
              value: ketchup
            potato:
              value: fries
```

## Expected Result

Keys in /test/example

## Actual Result

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'elektra'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/markus/libelektra/my-playbook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: set example values
      ^ here
```

## System Information

- Elektra Version: master
- Ansible 2.10.8

**Comment by markus2330** [comment]
@kodebach can you reproduce this issue?

**Comment by kodebach** [comment]
Turns out the `ansible-libelektra` repo was not correctly structured for a Ansible Galaxy collection. This should now be fixed. Also Ansible doesn't automatically recognize modules from installed collections. I added a note to the examples about this.

Note: It seems this is the only way to update to the new version of the collection:
```sh
ansible-galaxy collection install --force elektra_initiative.libelektra
```
At least for me it didn't update without the `--force` option. This may be fixed in Ansible 2.11. See also https://github.com/ansible/ansible/issues/65699

**Comment by markus2330** [comment]
It does not solve my issue, though, after removing `.ansible`, it still says:

```
# rm -rf .ansible
# ansible-galaxy collection install --force elektra_initiative.libelektra
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'elektra_initiative.libelektra:0.2.0' to '/home/markus/.ansible/collections/ansible_collections/elektra_initiative/libelektra'
Downloading https://galaxy.ansible.com/download/elektra_initiative-libelektra-0.2.0.tar.gz to /home/markus/.ansible/tmp/ansible-local-342v07erbl9/tmp3lztjgpi
elektra_initiative.libelektra (0.2.0) was installed successfully
# ansible-playbook my-playbook.yml                                                                                                                                                             
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'elektra'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/markus/Projekte/Elektra/libelektra/my-playbook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: set example values
      ^ her
# find .ansible
.ansible
.ansible/tmp
.ansible/galaxy_token
.ansible/collections
.ansible/collections/ansible_collections
.ansible/collections/ansible_collections/elektra_initiative
.ansible/collections/ansible_collections/elektra_initiative/libelektra
.ansible/collections/ansible_collections/elektra_initiative/libelektra/MANIFEST.json
.ansible/collections/ansible_collections/elektra_initiative/libelektra/README.md
.ansible/collections/ansible_collections/elektra_initiative/libelektra/FILES.json
.ansible/collections/ansible_collections/elektra_initiative/libelektra/LICENSE
.ansible/collections/ansible_collections/elektra_initiative/libelektra/plugins
.ansible/collections/ansible_collections/elektra_initiative/libelektra/plugins/modules
.ansible/collections/ansible_collections/elektra_initiative/libelektra/plugins/modules/elektrafacts.py
.ansible/collections/ansible_collections/elektra_initiative/libelektra/plugins/modules/elektra.py
```



So we recommend the manual installation after all? Manually making a symlink to the module dir does not make much sense, does it?

**Comment by kodebach** [comment]
> Is the `--force` only for updates or that it works at all?

The first time you install it works without. Once I had a version installed, I always got "is already installed" without the `--force` option.

> It does not solve my issue, though, after removing .ansible, it still says:

Did you change the playbook as stated in the updated README? I.e. did you add this part?
```yml
collections:
  - elektra_initiative.libelektra
```

**Comment by markus2330** [comment]
The formatting of this line does not work in the README and says `yml collections` instead of `collections`.

Why not directly adding this into the two examples? Does it interfere with the manual installation?

**Comment by markus2330** [comment]
I did the changes in the README.md.

**Comment by kodebach** [comment]
> Does it interfere with the manual installation?

I haven't tried it, but I assume in this case Ansible would complain that it can't find the collection. An older version of Ansible not know about `collections` at all.

However, I agree having the example for the latest version in the README is the best approach.

Does the playbook work for you now? Is there anything left in this issue?

**Comment by markus2330** [comment]
> but I assume in this case Ansible would complain that it can't find the collection.

I tried adding some collections which do not exist and it did not complain.

> An older version of Ansible not know about collections at all.

The new README.md says Ansible 2.7 is required.

> Does the playbook work for you now? Is there anything left in this issue?

Everything we need for CM works perfectly now. Thanks a lot for uploading it to Ansible Galaxy. :fireworks:

**Comment by kodebach** [comment]
> The new README.md says Ansible 2.7 is required.

If I understand the docs correctly, collections only existed starting with 2.9 since they are only used with `ansible-galaxy`.

**Comment by markus2330** [comment]
I just tried with Ansible from Debian (package version 2.7.7+dfsg-1 but `ansible --version` says 2.10.8?), the playbook also works.
