### ISSUE TITLE
Cirrus/Fedora: additional python dependencies destroy check_external_example_* tests

### ISSUE THREAD

**Issue by dev2718** [ElektraInitiative/libelektra#4009]
The addition of the dnf dependencies `python-pip, python-wheel` in `scripts/docker/cirrus/fedora/Dockerfile` destroys the tests

- check_external_example_codegen_econf
- check_external_example_codegen_menu
- check_external_example_codegen_tree

raising:
```
./application: error while loading shared libraries: libelektra-meta.so.5: cannot open shared object file: No such file or directory
error: application could not read default config (spec).
```

### Findings

- The problem is independent of the fuse tool or its packaging; it persists even after the complete removal of it.
- Locally reproducible using Dockerfile in question without cirrus.

## Steps to Reproduce the Problem

Add `python3-pip, python3-wheel` dependencies to [/scripts/docker/cirrus/fedora/Dockerfile](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/docker/cirrus/fedora/Dockerfile), 
or alternatively only ``python3-pip`` with an additional call `pip install wheel` (as was removed in this [commit](https://github.com/ElektraInitiative/libelektra/pull/3996/commits/2966dff6d5a96ced33489a28141ab44e9d03e521)).

For example, see the following two commits:

- Commit https://github.com/ElektraInitiative/libelektra/pull/3996/commits/39bfdb6dbc8478ef685c490fd8ec94b223cfc808 with this problem, resulting in [this](https://cirrus-ci.com/task/5888456858533888) failing cirrus run.
- Commit https://github.com/ElektraInitiative/libelektra/pull/3996/commits/2966dff6d5a96ced33489a28141ab44e9d03e521, removing the dependencies, resulting in this passing [run](https://cirrus-ci.com/task/6286747362394112).

## Expected Result

The tests should still pass.

## Actual Result

The tests fail ([log](https://cirrus-ci.com/task/5888456858533888)).

## System Information

- Elektra Version: master, PR #3996
- Operating System or Docker Container? Docker Container (cirrus/Fedora)

**Comment by mpranj** [comment]
I fear that this happens on any update to the Dockerfile. I updated the Gradle version and hit the same problem.

Once cirrus clears the cached image this error will happen anyway.

**Comment by mpranj** [comment]
Was this issue really resolved by #3996 or was it closed by mistake?

**Comment by dev2718** [comment]
I fear it must have been a mistake, #3996 does not fix #4009.

**Comment by mpranj** [comment]
The `-lelektra-meta` helped indeed.
