### ISSUE TITLE
proposal: remove -N from tools

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4012]
`-N` was introduced to specify which namespace to be used for cascading keys in ambiguous cases. As we now decided to not allow ambiguous cases, having the namespace in front of the key or `-N` got synonyms (as far as I can see).

I propose to completely remove `-N`: if someone wants/needs to write a namespace, it must happen in front of the keys.

**Comment by markus2330** [comment]
Btw. I think `-N` in [check_distribution.sh](https://github.com/ElektraInitiative/libelektra/blob/f910d2345fda33ce269b28f07818ed840b8881de/tests/shell/check_distribution.sh) is misuse of `-N`. Probably we should offer functionality to extract namespace, basename and dirname from a key name to make writing such shellscripts easier.

I propose to add:

```
kdb basename user:/dir/base
#> base
kdb dirname user:/dir/base
#> /dir
kdb namespace user:/dir/base
#> user:
```

@kodebach What do you think (especially about consistency in terminology) and can you maybe help out rewriting check_distribution.sh?

**Comment by kodebach** [comment]
Generally, I'm for removing the `-N` option, as long as e.g. `kdb get user:/foo` actually uses `kdbGet ("/foo")` under the hood. Otherwise you can't do a `kdb get` on a specific namespace with the `spec` plugin active.

> Probably we should offer functionality to extract namespace, basename and dirname from a key name to make writing such shellscripts easier.
> 
> I propose to add: [...]

An example with more than on level between root and base would be beneficial. In your example it is not 100% clear how `kdb dirname user:/foo/bar/base` would behave.

In any case I would propose:

```
# Returns the last key name part
kdb basename user:/foo/bar/base
#> base

# Returns the key name without namespace and without the last part
kdb dirname user:/foo/bar/base
#> /foo/bar

# Returns just the namespace ...
kdb namespace user:/foo/bar/base
#> user

# or an empty string for cascading keys
kdb namespace /foo/bar/base
#> 
```

Returning the colon (`:`) from `kdb namespace` doesn't make sense IMO. It is _not_ part of the namespace, it is just a separator between namespace and key "path".

I would also add a version of `dirname` that keeps the namespace intact:

```
# Returns the key name with namespace, but without the last part
kdb dirkey user:/foo/bar/base
#> user:/foo/bar
```

> @kodebach [...] can you maybe help out rewriting check_distribution.sh?

I have no idea what this test does... Why do you think I would be any better at rewriting it than anybody else?

**Comment by dev2718** [comment]
Thank you both for the proposal;
I have implemented and documented

* `kdb namespace`
* `kdb basename`
* `kdb dirname` and
* `kdb dirkey`

in commit 82c734ec95391baa0a906a4cb90eb1f7d95b27ce, 

For `kdb namespace` I opted to include ':' as specified in the original proposal, otherwise code like this would need additional case distinctions:
``
kdb get $(kdb namespace $KEY1)$(kdb dirname $KEY2)
``

**Comment by kodebach** [comment]
> For `kdb namespace` I opted to include ':' as specified in the original proposal, otherwise code like this would need additional case distinctions:
> `kdb get $(kdb namespace $KEY1)$(kdb dirname $KEY2)`

Ah yes, combining to different keys isn't covered by `dirkey`. Maybe we don't add `dirkey` then. It doesn't really solve a problem.

For the `:` or not question, the solution might be a new flag, similar to the `-n/--no-newline` you already added:

```
# Returns just the namespace with colon ...
kdb namespace user:/foo/bar/base
#> user:

# ... or with out the colon
kdb namespace --no-colon user:/foo/bar/base
#> user
```

For cascading keys `--no-colon` doesn't change anything. We always return an empty string.

Adding this option may be a bit weird/hard because of the way `kdb` parses command-line options. So maybe for now we leave the colon in and if somebody wants the namespace without the colon they can use:

```sh
kdb namespace $KEY | sed 's/:$//g'
```

**Comment by dev2718** [comment]
I added the flag `-S/--no-separator` to `kdb namespace` acting as @kodebach described above. (This was the best option letter/option name I could think of not already in use). 

The whole proposal is now completely implemented as of 112513f07d85124434b943743e988b3a87f8482e, including updated tests and documentation; The CI checks are successful; The changes are ready for review.

**Comment by kodebach** [comment]
> I already created a PR

Ah, sorry I missed that. GitHub didn't show me that the commit is part of this PR.

**Comment by kodebach** [comment]
In principal I agree with the idea of keeping config minimal. However, I think sometimes you are taking the KISS a bit to far. We are talking about an _entirely optional_ command-line option here. If you don't know what it does just don't use it. In such a basic case, I think we can make an argument for convenience over pure minimalism. In fact if you really wanted the minimal solution, `kdb namespace` shouldn't exist at all. You can already use `sed`/`cut`  to split the name on the `:` or the first `/`.

> it is a generic name, so people might expect it can be used for other commands

This is entirely a problem with the way `kdb` command-line options are set up. IMHO it makes absolutely zero sense that _all_ options are share between commands. It should work like `git` (same as commands in `elektraGetOpts`).

> people might even expect it works on `kdb get`

Again, if anybody expects this. It is an entirely different problem. There is no reason to believe this is the case, unless a manpage or a `--help` command suggests it. By the same argument you could say people might expect `git rm --all` should work, because `git add --all` does.

> it uses plural, contrary to other similar options like `no-newline`

Well that is easy, enough to fix. You should probably mention that in the PR.

> please always check if an option is really necessary before you suggest it, especially if you are not implementing it.

I suggested the option because:
1. I would find it useful. It was just a suggestion. This is an open-source project. I don't tell people want they have to do.
2. IMO returning `user:` from `kdb namespace user:/foo` is wrong in principle. `user:` is not the namespace. The namespace is just `user`. Returning it with `user:` (by default) could lead to confusion. IMO this could actually lead to far more confusion than everything you have mentioned.

>  adding useless options are one of the worst mistakes you can do in configuration design

Again, I don't consider this option useless and if were deemed useless, I would make the same argument for `kdb namespace` itself. After all `kdb namespace $KEY` is just `echo $KEY | cut -d/ -f1`.

**Comment by markus2330** [comment]
> In principal I agree with the idea of keeping config minimal.

:fireworks: 

> In fact if you really wanted the minimal solution, kdb namespace shouldn't exist at all.

I agree, but, imho, *this* would take KISS too far, as it makes sense (from completeness point of view) to have a command for all parts of the key names (even if one of these commands is doing something trivial).

> I would find it useful. It was just a suggestion. This is an open-source project. I don't tell people want they have to do.

There would be no problem to make a proposal like I did in #4024 for you (in a separate issue). But if people are asking for help what to do we have a totally different situation: they take your suggestion very seriously, as you are one of the most experienced Elektra developer. So it is important that we distinguish what we find personally nice-to-have and what supports the goals of Elektra.

**Comment by markus2330** [comment]
Was fixed by @dev2718 :fireworks:
