### ISSUE TITLE
Move sync to libtools

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#571]
Move code of TreeViewModel::synchronize (and its helper methods) to libtools and create test cases for it (with provoked conflicts).

Goal is that we can test synchronization code without having to use the GUI and also for reuse in other apps.

**Comment by fberlakovich** [comment]
You mentioned a testcase that is similar to the behaviour of ```TreeViewModel::synchronize```. Do you remember which one? As far as I can tell the code in ```TreeViewModel::synchronize``` is equivalent to the ```INPUT_DO_MERGE``` branch in the example code of the ```kdbSet``` documentation.

**Comment by markus2330** [comment]
Tests under `tests/kdb` use KDB for access. `gtest/gtest-elektra.h` automatically mounts something for you where you write into. Iirc there is no testcase at the moment which provokes a conflict, but this should really easy to do:
```
KDB a;
KDB b;
a.get();
b.get();
a.set();
b.set(); // conflict if writing to same file
```
So you do not need multiple processes nor threads but only two `KDB` instances.

And yes, you are right:  the new synchronize should do what is sketched in the example.

**Comment by fberlakovich** [comment]
I implemented a first version of a merging KDB wrapper, but for some reason I cannot provoke a conflict in the tests:

	Key parent(testRoot, KEY_END);

	KDB first;
	KeySet secondReturned;
	first.get(firstReturned, parent);
	firstReturned.append(Key ("system" + testRoot + "key1", KEY_VALUE, "value1", KEY_END));

	KDB second;
	KeySet firstReturned;
	second.get(secondReturned, parent);
	secondReturned.append(Key ("system" + testRoot + "key2", KEY_VALUE, "value2", KEY_END));

	second.set(secondReturned, parent);
	first.set(firstReturned, parent); // exception expected

The test uses the exact same setup as the tests in testkdb_simple. When stepping in the debugger I can see that the file is created after ```second.set``` and simply overwritten after ```first.set```.

Any ideas?

**Comment by markus2330** [comment]
Thus the identity of the processes is the same (pid+tid) and not concurrent the conflict can only be detected by the time stamp when the file was modified.

So: Maybe your filesystem has time stamps deactivated? Or your VM makes weird time jumps? Or its granularity of time measurement is to low, try to sleep for some time and set again. Or try to mount it on tmpfs.

For me:
```
	kdb::KDB kdb;
	kdb::KDB kdb2;

	kdb.get (ks, "/test");
	kdb2.get (ks, "/test");
	ks.append (kdb::Key ("system/test/key", KEY_VALUE, "value", KEY_END));
	kdb.set (ks, "/test");
	ks.append (kdb::Key ("system/test/key2", KEY_VALUE, "value2", KEY_END));
	kdb2.set (ks, "/test");
```

->

```
terminate called after throwing an instance of 'kdb::KDBException'
  what():  Error (#30) occurred!
Description: A conflict occurred: another process modified the key database.
Ingroup: plugin
Module: resolver
At: /home/markus/Projekte/Elektra/current/src/plugins/resolver/resolver.c:665
Reason: conflict, file modification time stamp 1460492862.945422248 is different than our time stamp 1460492862.933422264, config file name is "/etc/kdb/ni", our identity is uid: 500, euid: 500, gid: 500, egid: 500
Mountpoint: system/test
Configfile: /etc/kdb/ni.25657:1460492862.925290.tmp
```

**Comment by fberlakovich** [comment]
> So: Maybe your filesystem has time stamps deactivated? Or your VM makes weird time jumps? Or its granularity of time measurement is to low, try to sleep for some time and set again. Or try to mount it on tmpfs.
> 
> For me:

Thanks for the hint, it works now but I don't really understand why. My code sample uses the same parent key datastructure for both ```kdb.get``` calls whereas your sample uses the keyname overload of ```kdb.get```. As soon as I use the keyname overload, the code behaves as expected.

**Comment by markus2330** [comment]
Mmmh, I am not sure what you did, the code as above does not compile (‘firstReturned’ is declared later than used). If it is not about the time resolution of the file (which is a known but unresolvable problem) there might be a bug.

But maybe only one of your ks was empty and thus kdbSet() removed the file and the other kdbSet() created it. This would be expected behaviour, at least how the resolver works now. (One could argue that this should be a conflict, too).

A new way of conflict detection is tried out by Kurt in #578, it does not rely on time stamps (but creates additional files for conflict detection). But I think its not ready to try it out.

**Comment by fberlakovich** [comment]
> Mmmh, I am not sure what you did, the code as above does not compile (‘firstReturned’ is declared later than used). If it is not about the time resolution of the file (which is a known but unresolvable problem) there might be a bug.

Sorry, seems like I mixed up the code while copying. I thought I got it working (i.e. failing), but the conflict does not occur anymore :(. 

This test passes (although it should not) no matter how long I wait between each instruction:

	class MergingKDBTest : public ::testing::Test
	{
	protected:
		static const std::string testRoot;
		static const std::string configFile;

		testing::Namespaces namespaces;
		testing::MountpointPtr mp;

		MergingKDBTest () : namespaces ()
		{
		}

		virtual void SetUp () override
		{
			mp.reset (new testing::Mountpoint (testRoot, configFile));
		}

		virtual void TearDown () override
		{
			mp.reset ();
		}
	};

	const std::string MergingKDBTest::configFile = "kdbFile.dump";
	const std::string MergingKDBTest::testRoot = "/tests/kdb/";


	TEST_F (MergingKDBTest, ThrowsExceptionIfMergeNotPossible)
	{
		Key parent(testRoot, KEY_END);

		KDB first;
		KeySet firstReturned;
		first.get(firstReturned, parent);

		KDB second;
		KeySet secondReturned;
		second.get(secondReturned, parent);

		firstReturned.append(Key ("system" + testRoot + "key1", KEY_VALUE, "value1", KEY_END));
		secondReturned.append(Key ("system" + testRoot + "key2", KEY_VALUE, "value2", KEY_END));

		second.set(secondReturned, parent);
		first.set(firstReturned, parent);
	}

I cannot find any clue why it behaves this way, even when stepping through the resolver. However, I need a provoked conflict in order to test the merging logic.

**Comment by markus2330** [comment]
Thank you, you are right: there seems to be a bug. I pushed a working and a non-working example.

But there is a working example (I already posted it before, now also in `tests/kdb/testkdb_simple.cpp ThrowsExceptionCorrectly`), so you simply continue your tests with the working case.

If even this working case does not work for you, see tipps above how to get it work. (It must be a time stamp issue then, at least when all build servers also say it works for them.) For me it works reliable.

**Comment by fberlakovich** [comment]
> If even this working case does not work for you, see tipps above how to get it work. (It must be a time stamp issue then, at least when all build servers also say it works for them.) For me it works reliable.

It still does not behave completely reliable for me, but I will investigate it further. Most likely it is an issue with my setup now. Sorry for the delay, but without reliable test cases I cannot test the actual merging code reliably. However, if you wish I can push an unfinished pull-request that outlines my idea for encapsulating the merger.

**Comment by markus2330** [comment]
Yes, the build server has issues, too. The issue seems to be more severe than I thought initally. (On my computer it only happens with some specific test cases, in others it works reliable) You could use to use the error plugin to trigger an error, but the setup might behave differently.

@tom-wa did you find out something about this issue in your NFS investigations?

**Comment by markus2330** [comment]
It really is a conflict "file not there" vs. "file there", which is not handled and obviously cannot be handled by time stamps. It worked for me earlier, because I already had a config file (and did not had the same kind of conflict you had).

As workaround, you can simply create a configFile, then you get a conflict (see 25f3068c47034bd9e8d51209205443b3fa316e9f).

But you are right: the expected behavior is that no-file/file conflicts should be reported, too. Thus it should be fixed for this release.

**Comment by markus2330** [comment]
both conflicts "file there" vs. "file not there" should now be handled.

**Comment by fberlakovich** [comment]
Can we close the ticket? #611 is an independent ticket anyway.
