### ISSUE TITLE
qt-gui fails to synchronize because of readonly plugins

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#603]
When trying to synchrinize in the qt-gui (even without changes) it displays the following error message

`Error (#84) occurred!
Description: Read only plugin, kdbSet not supported
Ingroup: kdb
Module: 
At: /home/felixl/development/elektra/libelektra/src/libs/elektra/plugin.c:390
Reason: the key system/elektra/version/constants/KDB_VERSION (expected system/elektra/version) was modified to 0.8.15 (expected Below are version information of the Elektra Library you are currently using)
Mountpoint: system/elektra/version
Configfile: 
`

This may be a regression of #208, but it seems that this time no saving at all is possible.

**Comment by markus2330** [comment]
I can confirm the issue:
```
1 Warning was issued:
 Warning number: 36
	Description: could not unlink file
	Ingroup: plugin
	Module: resolver
	At: /home/markus/Projekte/Elektra/current/src/plugins/resolver/resolver.c:982
	Reason: the file "/etc/hosts.8005:1460995548.766905.tmp" because of "Datei oder Verzeichnis nicht gefunden"
	Mountpoint: system/hosts
	Configfile: 
Error (#84) occurred!
Description: Read only plugin, kdbSet not supported
Ingroup: kdb
Module: 
At: /home/markus/Projekte/Elektra/current/src/libs/elektra/plugin.c:390
Reason: the key system/elektra/version/constants/KDB_VERSION (expected system/elektra/version) was modified to 0.8.15 (expected Below are version information of the Elektra Library you are currently using)
Mountpoint: system/elektra/version
Configfile: 
```

I cannot reproduce it using the kdb tool, setting the same text again works without error:
```
kdb set system/elektra/version/constants/KDB_VERSION 0.8.15
```

@0003088 do you have any idea? Does it also occur on your installation?

**Comment by 0003088** [comment]
I can reproduce the bug with qt5.6. I will try to figure out what happens. Any clue as to the time the bug appeared for the first time?

**Comment by markus2330** [comment]
It slipped in during 0.8.14..0.8.15. So 0.8.15 was unfortunately released with this bug. Do you have some idea which commit it could be or do we need git-bisect?

**Comment by 0003088** [comment]
No idea, really. It's a strange error, could it have something to do with encoding or something? The string from the gui is initially a  QString and the error occurs in a c file, maybe something went wrong on the way.

**Comment by fberlakovich** [comment]
I did a git bisect and it seems like the issue was introduced in 3d073e75c4b67f4f2bec922a581bd94458b44dfb.

**Comment by markus2330** [comment]
@fberlakovich Thank you,

```
diff --git a/src/tools/qt-gui/src/treeviewmodel.cpp b/src/tools/qt-gui/src/treeviewmodel.cpp
index 5806081..243fbb4 100644
--- a/src/tools/qt-gui/src/treeviewmodel.cpp
+++ b/src/tools/qt-gui/src/treeviewmodel.cpp
@@ -454,11 +454,6 @@ void TreeViewModel::sink (ConfigNodePtr node, QStringList keys, const Key & key)
 
        if (node->hasChild (name) && !node->getChildByName (name)->isDirty ())
        {
-               if (node->getChildByName (name)->getKey ())
-               {
-                       node->getChildByName (name)->updateNode (key);
-               }
-
                sink (node->getChildByName (name), keys, key);
        }
        else
```

fixes the problem. @0003088 What was the purpose of adding these lines? Is this a correct fix or does it introduce other problems?

@0003088 can you create a PR for this release? (e.g. fixing some problems including this one?)

**Comment by 0003088** [comment]
As far as I remember the purpose of these lines was to update the gui nodes when a user changed a key with the kdb tool, the change would only show up on the next gui restart and not on sync. May I ask what happens if a key is overwritten by a (identical) duplicate of itself? Is the key then regarded as changed?

**Comment by markus2330** [comment]
Yes, duplicating sets the sync flag and appending would replace the key with the new one. Then the keyset would be considered as changed.

But in this bug we do not only have a unnecessary change but it rather seems like a complete key is missing.

**Comment by markus2330** [comment]
Appending exactly the same key (with same address), however, would be a NOP.

**Comment by 0003088** [comment]
So we want to detect if two keys are the same by their name and values but not identical, since key != key.dup(). Is there an efficient way to do this or should it be done by comparing names and values separately?

**Comment by markus2330** [comment]
Ideally you should not duplicate keys, except when they are actually changed. And operator== actually compares by content, not by address.

**Comment by 0003088** [comment]
But if == compares by content, would't that mean key == key.dup()?

**Comment by 0003088** [comment]
This was an incredible stupid bug on my part... Needs some further testing I suppose

**Comment by markus2330** [comment]
Ok, thank you! Would be great to see the PR soon!

**Comment by markus2330** [comment]
Btw. also describe what the wrong behaviour is (any why these lines were added)

**Comment by 0003088** [comment]
I did not remove these lines, I just added a necessary check that I missed. I did some quick tests and it works as far as I can see (including syncing keys that a kdb user would create/alter)

**Comment by markus2330** [comment]
Sounds great, can you create a PR?

**Comment by 0003088** [comment]
Just trying to. Unfortunately I pushed the changes I made regarding the new buttons too and the gui wont compile atm. Should I just create the request regardless and you cherry-pick the fix or should I resolve it locally and push the fix only?

**Comment by markus2330** [comment]
You still have some time (there are still other bugs open), so if you want you can finish the buttons. Otherwise it would be good if you can resolve it locally. Otherwise I might do mistakes when cherry picking.

**Comment by 0003088** [comment]
I do not have the time to finish the buttons tonight. I will revert the commits regarding the buttons and push only the fix.

**Comment by markus2330** [comment]
The release won't happen today, so you would have time tomorrow, too. If its a good idea is of course dependent on the implementation state of the buttons, its certainly better to have the fix today than nothing tomorrow ;)
